config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#about_me'

  scope '(:locale)', locale: /en|fr/ do
    get 'about_me', to: 'home#about_me'
    get 'download_resume', to: 'home#download_resume'
    get 'resume', to: 'home#resume'
    get 'portfolio', to: 'home#portfolio'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || extract_locale_from_accept_language_header || I18n.default_locale
    I18n.locale = locale
    I18n.with_locale(locale, &action)
  end

  private

  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def about_me
  end

  def resume
    @age = DateCalculations.years_since(Date.new(1997, 7, 19))
  end

  def portfolio
  end

  def download_resume
    send_file "#{Rails.root}/files/CV.pdf", filename: 'resume.pdf', type: 'application/pdf'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def navigation_links(mobile: false)
    links = [
      { url: about_me_path, text: t('navbar.about_me'), controller: 'home#about_me' },
      { url: resume_path, text: t('navbar.resume'), controller: 'home#resume' },
      { url: portfolio_path, text: t('navbar.portfolio'), controller: 'home#portfolio' },
      { url: malt_url, text: t('navbar.contact_me'), options: { target: '_blank' } }
    ]

    links.map { |link| link_html(link, active: active_page?(link), mobile:) }.join.html_safe
  end

  def render_svg(path)
    File.open(Rails.root.join("app/assets/svg/#{path}.svg"), 'rb') do |file|
      raw file.read
    end
  end

  def switch_locale_url
    new_locale = locale == :en ? :fr : :en

    url_for(locale: new_locale)
  end

  private

  def active_page?(link)
    current_page?(link[:url]) || link[:controller] == "#{controller.controller_name}##{controller.action_name}"
  end

  def link_html(link, active: false, mobile: false)
    classes = if active && mobile
                mobile_active_nav_item_classes
              elsif active
                active_nav_item_classes
              elsif mobile
                mobile_nav_item_classes
              else
                nav_item_classes
              end

    link_to link[:text], link[:url], class: classes, **(link[:options] || {})
  end

  def nav_item_classes
    <<~CLASSES.squish
      text-gray-700 dark:text-gray-300 hover:bg-slate-300 dark:hover:bg-gray-800 hover:text-slate-700
      dark:hover:text-white rounded-md px-3 py-2 text-sm font-medium
    CLASSES
  end

  def active_nav_item_classes
    <<~CLASSES.squish
      bg-gray-900 dark:bg-indigo-800 text-white rounded-md px-3 py-2 text-sm font-medium
    CLASSES
  end

  def mobile_nav_item_classes
    <<~CLASSES.squish
      text-gray-700 dark:text-gray-300 hover:bg-slate-300 dark:hover:bg-gray-700 hover:text-white block rounded-md
      px-3 py-2 text-base font-medium
    CLASSES
  end

  def mobile_active_nav_item_classes
    <<~CLASSES.squish
      bg-gray-900 dark:bg-indigo-800 text-white block rounded-md px-3 py-2 text-base font-medium
    CLASSES
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def malt_url
    'https://www.malt.fr/profile/maxencetisserant/'
  end

  def github_url
    'https://github.com/tisserm/'
  end

  def linkedin_url
    'https://www.linkedin.com/in/maxence-tisserant/'
  end
end

app/views/home/about_me.html.erb
<div class="w-full mb-8">
  <h1 class="text-center text-4xl mb-8"><%= t 'about_me.header' %></h1>

  <figure class="flex flex-col lg:flex-row px-4" aria-label="About me section">
    <div class="lg:w-4/12">
      <%= image_tag 'me.jpg', class: 'rounded-full w-40 h-40 lg:w-60 lg:h-60 object-cover mx-auto my-5 shadow-xl', aria: { label: 'Picture of myself' }, alt: 'A picture of me' %>
    </div>

    <div class="lg:w-8/12 self-center text-center lg:text-left">
      <p class="text-gray-600 dark:text-gray-400 mb-3 text-sm"><%= t 'about_me.short_description' %></p>
      <p class="text-xl font-bold mb-3">Maxence Tisserant</p>

      <div class="mb-3 flex gap-4 justify-center lg:justify-start">
        <%= link_to malt_url, aria: { label: 'Link to my profile on Malt' }, target: '_blank' do %>
          <%= image_tag 'malt.svg', class: 'w-10 h-auto dark:invert', role: 'link', tabindex: 0, aria: { label: 'Malt logo' }, alt: 'Malt logo' %>
        <% end %>
        <%= link_to github_url, aria: { label: 'Link to my profile on Github' }, target: '_blank' do %>
          <%= image_tag 'github.svg', class: 'w-10 h-auto dark:invert', role: 'link', tabindex: 0, aria: { label: 'Github logo' }, alt: 'Github logo' %>
        <% end %>
        <%= link_to linkedin_url, aria: { label: 'Link to my profile on Linkedin' }, target: '_blank' do %>
          <%= image_tag 'linkedin.svg', class: 'w-10 h-auto dark:invert', role: 'link', tabindex: 0, aria: { label: 'Linkedin logo' }, alt: 'Linkedin logo' %>
        <% end %>
      </div>

      <p class="text-left mb-3">
        <%= t 'about_me.introduction' %>
      </p>

      <p class="text-left mb-3">
        <%= t 'about_me.short_resume' %>
      </p>

      <div class="flex justify-center lg:justify-start gap-4 mt-3">
        <%= link_to download_resume_path do %>
          <button type="button" class="text-lg inline-flex items-center rounded-md bg-gray-900 dark:bg-indigo-800 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 dark:hover:bg-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-900 dark:focus-visible:outline-indigo-800">
            <%= t 'about_me.download_resume' %>
          </button>
        <% end %>
        <%= link_to malt_url, target: '_blank' do %>
          <button type="button" class="text-lg inline-flex items-center rounded-md bg-gray-900 dark:bg-indigo-800 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 dark:hover:bg-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-900 dark:focus-visible:outline-indigo-800">
            <%= t 'about_me.contact_me' %>
          </button>
        <% end %>
      </div>
    </div>
  </figure>
</div>

app/views/home/portfolio.html.erb
<div class="w-full">
  <h1 class="text-center text-4xl mb-8"><%= t 'portfolio.header' %></h1>

  <h2 class="text-center text-2xl my-8 mt-14"><%= t 'portfolio.opensource_projects_header' %></h2>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 px-5">
    <% t('portfolio.opensource_projects').each do |opensource_project| %>
      <%= link_to opensource_project[:link], target: '_blank' do %>
        <div class="rounded-md border-2 dark:border-gray-300 border-gray-700 min-h-24">
          <div class="bg-[#e9573f] dark:bg-[#B94A3F] min-h-10 p-2 rounded-t flex items-center justify-center gap-2">
            <%= render_svg opensource_project[:logo] %>
            <span class=""><%= opensource_project[:name] %></span>
          </div>
          <div class="h-px bg-black dark:bg-gray-300">
          </div>
          <div class="p-2">
            <%= opensource_project[:description] %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <h2 class="text-center text-2xl my-8 mt-14"><%= t 'portfolio.previous_projects_header' %></h2>

  <h3 class="text-center text-xl my-5 dark:text-slate-400 text-gray-700"><%= t 'portfolio.soon' %></h3>
</div>

app/views/home/resume.html.erb
<div class="w-full mb-8">
  <h1 class="text-center text-4xl mb-8"><%= t 'resume.header' %></h1>

  <div class="relative">
    <span class="block absolute w-1 top-0 bottom-0 left-1/3 sm:left-1/4 bg-gray-400 dark:bg-slate-200 rounded-full mt-1" aria-hidden="true"></span>

    <div class="relative">
      <div class="block absolute -ml-1.5 w-4 h-4 top-1 bottom-0 left-1/3 sm:left-1/4 rounded-full bg-gray-900 dark:bg-indigo-600" aria-hidden="true"></div>
      <div class="flex">
        <div class="basis-1/3 sm:basis-1/4 pr-7 text-right">1997</div>
        <div class="basis-2/3 sm:basis-3/4 pl-7">
          <%= t 'resume.birth', age: @age %>
        </div>
      </div>
    </div>

    <div class="relative mt-4">
      <div class="relative absolute -ml-1.5 w-4 h-4 top-1 bottom-0 left-1/3 sm:left-1/4 bg-slate-50 dark:bg-slate-800 rotate-90" aria-hidden="true">
        <div class="block absolute w-1 h-4 top-0 bottom-0 left-0 bg-gray-400 dark:bg-slate-200" aria-hidden="true"></div>
        <div class="block absolute w-1 h-4 top-0 bottom-0 right-0 bg-gray-400 dark:bg-slate-200" aria-hidden="true"></div>
      </div>
    </div>

    <div class="relative mt-7">
      <div class="block absolute -ml-1.5 w-4 h-4 top-1 bottom-0 left-1/3 sm:left-1/4 rounded-full bg-gray-900 dark:bg-indigo-600" aria-hidden="true"></div>
      <div class="flex">
        <div class="basis-1/3 sm:basis-1/4 pr-7 text-right">09/2015 - 07/2020</div>
        <div class="basis-2/3 sm:basis-3/4 pl-7">
          <strong><%= t 'resume.education.header' %></strong>
          <br />
          <%= t 'resume.education.content_html' %>
        </div>
      </div>
    </div>

    <div class="relative mt-7">
      <div class="block absolute -ml-1.5 w-4 h-4 top-1 bottom-0 left-1/3 sm:left-1/4 rounded-full bg-gray-900 dark:bg-indigo-600" aria-hidden="true"></div>
      <div class="flex">
        <div class="basis-1/3 sm:basis-1/4 pr-7 text-right">09/2019 - 02/2024</div>
        <div class="basis-2/3 sm:basis-3/4 pl-7">
          <strong><%= t 'resume.manda_job.header' %></strong>
          <br />
          <%= t 'resume.manda_job.content_html' %>
          <ul class="list-disc list-inside">
            <% t('resume.manda_job.tasks').each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="relative mt-7">
      <div class="block absolute -ml-1.5 w-4 h-4 top-1 bottom-0 left-1/3 sm:left-1/4 rounded-full bg-gray-900 dark:bg-indigo-600" aria-hidden="true"></div>
      <div class="flex">
        <div class="basis-1/3 sm:basis-1/4 pr-7 text-right">03/2024 - <%= t 'resume.future.today' %></div>
        <div class="basis-2/3 sm:basis-3/4 pl-7">
          <strong><%= t 'resume.future.header' %></strong>
          <br />
          <%= t 'resume.future.content_html' %>
          <%= link_to malt_url, class: 'underline', aria: { label: 'Link to my profile on Malt' } do %>
            <%= t 'resume.future.contact_me' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <h1 class="text-center text-4xl mb-8 mt-14 dark:stroke-transparent"><%= t 'skills.header' %></h1>

  <div class="flex md:flex-row flex-col justify-around mx-5">
    <div class="min-w-64">
      <h2 class="text-2xl my-5"><%= t 'skills.tech_skills.header' %></h2>

      <div class="max-w-md">
        <% t('skills.tech_skills.skills').each do |skill| %>
          <div class="flex gap-4">
            <span class="basis-1/2">
              <%= skill[:name] %>
            </span>
            <div class="flex basis-1/2">
              <% skill[:rating].times do %>
                <%= render_svg 'star' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="min-w-64">
      <h2 class="text-2xl my-5"><%= t 'skills.languages.header' %></h2>

      <div class="max-w-md">
        <% t('skills.languages.skills').each do |skill| %>
          <div class="flex gap-4">
            <span class="basis-1/2">
              <%= skill[:name] %>
            </span>
            <div class="flex basis-1/2">
              <% skill[:rating].times do %>
                <%= render_svg 'star' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="flex justify-center gap-4 mt-14">
    <%= link_to download_resume_path do %>
      <button type="button" class="text-lg inline-flex items-center rounded-md bg-gray-900 dark:bg-indigo-800 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 dark:hover:bg-indigo-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-900 dark:focus-visible:outline-indigo-800">
        <%= t 'resume.download_resume' %>
      </button>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= Rails.env.development? ? '[DEV] ' : '' %><%= t 'title' %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-50 dark:bg-slate-800 text-gray-900 dark:text-gray-100" data-controller="dark-mode">
    <%= render partial: 'shared/navbar' %>

    <main class="container mx-auto mt-20 px-5 flex z-0">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-slate-200 dark:bg-gray-700 sticky top-0 z-50" data-controller="navbar" aria-label="Navigation bar">
  <div class="mx-auto max-w-7xl px-2 md:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center md:hidden">
        <% # Mobile menu button %>
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-700 dark:text-gray-300 hover:bg-slate-300 dark:hover:bg-gray-700 dark:hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-slate-500 dark:focus:ring-white" aria-controls="mobile-menu" aria-expanded="false" data-action="navbar#toggleMenu" tabindex="0">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <% # Closed menu icon %>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-navbar-target="closeIcon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <% # Opened menu icon %>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-navbar-target="openIcon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <% # Desktop menu %>
      <div class="flex flex-1 items-center justify-center md:items-stretch md:justify-start">
        <div class="hidden md:ml-6 md:block">
          <div class="flex space-x-4">
            <%= navigation_links(mobile: false) %>
          </div>
        </div>
      </div>
      <% # Translate icon container %>
      <div class="flex items-center pr-2 md:static md:inset-auto md:ml-6 md:pr-0">
        <a href="<%= switch_locale_url %>" class="relative rounded-full bg-slate-200 dark:bg-gray-700 p-1 text-gray-700 dark:text-gray-300 dark:hover:bg-gray-700 dark:hover:text-white focus:outline-none focus:ring-2 focus:ring-slate-500 dark:focus:ring-white focus:ring-offset" tabindex="0">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">Toggle language between french and english</span>
          <% # Translate icon %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" aria-label="Toggle language between french and english">
            <path stroke-linecap="round" stroke-linejoin="round" d="m10.5 21 5.25-11.25L21 21m-9-3h7.5M3 5.621a48.474 48.474 0 0 1 6-.371m0 0c1.12 0 2.233.038 3.334.114M9 5.25V3m3.334 2.364C11.176 10.658 7.69 15.08 3 17.502m9.334-12.138c.896.061 1.785.147 2.666.257m-4.589 8.495a18.023 18.023 0 0 1-3.827-5.802" />
          </svg>
        </a>
      </div>
      <% # Moon/sun icons container %>
      <div class="flex items-center pr-2 md:static md:inset-auto md:ml-6 md:pr-0">
        <button type="button" class="relative rounded-full bg-slate-200 dark:bg-gray-700 p-1 text-gray-700 dark:text-gray-300 dark:hover:bg-gray-700 dark:hover:text-white focus:outline-none focus:ring-2 focus:ring-slate-500 dark:focus:ring-white focus:ring-offset" data-action="dark-mode#toggleTheme" tabindex="0">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">Toggle dark mode</span>
          <% # Moon icon %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" data-dark-mode-target="darkModeIcon" aria-label="Switch to dark mode" role="img">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
          </svg>
          <% # Sun icon %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="hidden w-6 h-6" data-dark-mode-target="lightModeIcon" aria-label="Switch to light mode" role="img">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <% # Mobile menu %>
  <div class="md:hidden hidden" id="mobile-menu" data-navbar-target="mobileMenu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <%= navigation_links(mobile: true) %>
    </div>
  </div>
</nav>

app/views/shared/svg/_star.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="#fef08a" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 dark:stroke-transparent">
  <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 0 0-.182.557l1.285 5.385a.562.562 0 0 1-.84.61l-4.725-2.885a.562.562 0 0 0-.586 0L6.982 20.54a.562.562 0 0 1-.84-.61l1.285-5.386a.562.562 0 0 0-.182-.557l-4.204-3.602a.562.562 0 0 1 .321-.988l5.518-.442a.563.563 0 0 0 .475-.345L11.48 3.5Z" />
</svg>